import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const html = readFileSync(new URL('../site/index.html', import.meta.url), 'utf8');
const app = readFileSync(new URL('../site/app.js', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../site/styles.css', import.meta.url), 'utf8');
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');

describe('site copy and labels', () => {
  it('keeps quick-check result ownership dynamic instead of demo-labeled', () => {
    expect(html).toContain('id="quick-result-label"');
    expect(html).not.toContain('>Default artifact<');
    expect(app).toContain('setText("quick-result-label", quickResultLabel(result));');
    expect(app).toContain('function quickResultLabel(result)');
    expect(app).toContain('"Your QA finding"');
    expect(app).toContain('"Seeded example finding"');
  });

  it('keeps the first screen centered on the note checker with clear public jobs', () => {
    const summarySection = html.match(/<section class="summary-band">[\s\S]*?<\/section>/)?.[0] || '';
    const quickCheckIndex = summarySection.indexOf('class="quick-check-panel"');

    expect(quickCheckIndex).toBeGreaterThan(-1);
    expect(summarySection).toContain('<h1 id="quick-check-title">Did the AI scribe make up care?</h1>');
    expect(summarySection).toContain('Did the AI scribe make up care?');
    expect(summarySection).toContain('For people with the evidence in hand');
    expect(summarySection).toContain('paste the encounter source');
    expect(summarySection).toContain('and AI note');
    expect(summarySection).toContain('ScribeBench flags unsupported care');
    expect(summarySection).toContain('writes the QA');
    expect(summarySection).toContain('finding a reviewer can act on');
    expect(summarySection).toContain('class="purpose-line"');
    expect(summarySection).toContain('ScribeBench public-use contract');
    expect(summarySection).toContain('Use it for');
    expect(summarySection).toContain('Check one AI-scribe note, challenge a public claim, or prepare aggregate evidence.');
    expect(summarySection).toContain('You leave with');
    expect(summarySection).toContain('A copyable QA finding, evidence ask, blocker receipt, or scores-only row.');
    expect(summarySection).toContain('Who this is for');
    expect(summarySection).toContain('Clinical QA, AI-scribe buyers, builders, and NapierMD build-in-public readers with evidence in hand.');
    expect(summarySection).toContain('class="purpose-boundary"');
    expect(summarySection).toContain('Do not use it for');
    expect(summarySection).toContain('Patient advice, PHI storage, clinical clearance, or ranking current models from old rows.');
    expect(summarySection).toContain('class="quick-artifact-preview"');
    expect(summarySection).toContain('Example ScribeBench QA finding');
    expect(summarySection).toContain('Example QA finding');
    expect(summarySection).toContain('Hold this note before signing.');
    expect(summarySection).toContain('The copied packet is a review artifact, not a vague score.');
    expect(summarySection).toContain('class="quick-artifact-preview-grid"');
    expect(summarySection).toContain('Decision');
    expect(summarySection).toContain('Hold or edit the note.');
    expect(summarySection).toContain('Evidence');
    expect(summarySection).toContain('Note says head CT; source says no head strike.');
    expect(summarySection).toContain('Boundary');
    expect(summarySection).toContain('One source-note pair, not a system claim.');
    expect(summarySection).toContain('Verify the gap before signing or citing.');
    expect(summarySection).toContain('quick-entry-paths');
    expect(summarySection).toContain('Choose the ScribeBench job');
    expect(summarySection).toContain('I have source + note');
    expect(summarySection).toContain('Check one AI-scribe note');
    expect(summarySection).toContain('Paste both sides and leave with a reviewer handoff plus QA finding.');
    expect(summarySection).toContain('<a href="#quick-check-form" data-quick-start-own>Paste my note</a>');
    expect(summarySection).toContain('Paste my note');
    expect(summarySection).toContain('I heard a claim');
    expect(summarySection).toContain('Challenge the promise');
    expect(summarySection).toContain('Turn "safe," "hallucination-free," or "best" into the evidence it would need.');
    expect(summarySection).toContain('Build evidence ask');
    expect(summarySection).toContain('I can add proof');
    expect(summarySection).toContain('Publish aggregate evidence');
    expect(summarySection).toContain('Use the harness to submit a scores-only current-system row people can cite.');
    expect(summarySection).toContain('Prepare row');
    expect(summarySection).toContain('quick-start-strip');
    expect(summarySection).toContain('Seeded catch visible now');
    expect(summarySection).toContain('The AI note invented a negative head CT and a syncope workup.');
    expect(summarySection).toContain('Seeded source-note contradiction');
    expect(summarySection).toContain('Note says');
    expect(summarySection).toContain('CT head was negative; orthostatics, telemetry, and TSH were ordered for syncope.');
    expect(summarySection).toContain('Source says');
    expect(summarySection).toContain('Mechanical rug trip; no head strike and no loss of consciousness.');
    expect(summarySection).toContain('Copyable finding: this note claims a workup the source never documents.');
    expect(summarySection).toContain('Check my note');
    expect(summarySection).toContain('quick-start-copy-receipt');
    expect(summarySection).toContain('Copy seeded finding');
    expect(summarySection).toContain('Open demo finding');
    expect(summarySection).toContain('quick-start-copy-status');
    expect(summarySection).toContain('quick-start-copy-panel');
    expect(summarySection).toContain('Manual copy fallback');
    expect(summarySection).toContain('Clipboard access is unavailable here.');
    expect(summarySection).toContain('Select this finding and paste it into the next review thread.');
    expect(summarySection).toContain('quick-start-copy-fallback');
    expect(summarySection).toContain('ScribeBench demo QA finding');
    expect(summarySection).not.toContain('class="intro-panel"');
    expect(summarySection).not.toContain('class="use-case-strip"');
    expect(summarySection).not.toContain('class="public-contract"');
    expect(summarySection).not.toContain('class="start-router"');
    expect(summarySection).not.toContain('class="hero-proof-trail"');
    expect(summarySection).not.toContain('NapierMD public clinical AI QA');
    expect(summarySection).not.toContain('Plain-English ScribeBench answer');
    expect(summarySection).not.toContain('This is a receipt generator for AI-scribe evidence.');
    expect(summarySection).not.toContain('Choose the next job');
    expect(summarySection).not.toContain('What do you need to leave with?');
    expect(summarySection).not.toContain('Copy route plan');
    expect(summarySection).not.toContain('Read the NapierMD proof trail');
    expect(styles).toContain('.quick-proof-pair');
    expect(styles).toContain('.purpose-line .purpose-boundary');
    expect(styles).toContain('.purpose-line .purpose-boundary span');
    expect(styles).toContain('.quick-artifact-preview');
    expect(styles).toContain('.quick-artifact-preview-grid');
    expect(styles).toContain('.quick-artifact-preview-grid div:nth-child(2n)');
    expect(styles).toContain('.quick-artifact-preview {\n    order: 5;');
    expect(styles).toContain('.quick-result {\n    order: 6;');
    expect(styles).toContain('.quick-entry-paths');
    expect(styles).toContain('.quick-entry-paths article');
    expect(styles).toContain('.quick-entry-paths article:last-child');
    expect(styles).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));');
    expect(styles).toContain('.quick-proof-pair div:last-child');
    expect(styles).toContain('.quick-check-panel {\n    order: 1;');
    expect(styles).toContain('.purpose-line {\n    order: 3;');
    expect(styles).toContain('.quick-check-form {\n    order: 4;');
    expect(styles).toContain('.quick-start-strip {\n    order: 7;');
    expect(styles).toContain('.quick-entry-paths {\n    order: 8;');
    expect(styles).toContain('.mobile-proof {\n    order: 9;');
    expect(styles).toContain('.quick-capability-grid {\n    order: 11;');
    expect(styles).toContain('.quick-entry-paths p {\n    display: none;');
    expect(styles).toContain('.quick-entry-paths article:first-child a');
    expect(styles).toContain('background: var(--accent);');
    expect(styles).not.toContain('.quick-purpose-strip');
    expect(styles).not.toContain('.quick-origin-note');
    expect(styles).toContain('.quick-start-copy-fallback');
    expect(styles).toContain('.quick-start-copy-panel');
    expect(styles).toContain('.quick-copy-panel');
    expect(styles).toContain('grid-template-columns: minmax(0, 1.08fr) minmax(360px, 0.92fr);');
    expect(styles).toContain('.quick-check-panel {\n  grid-column: 1;\n  grid-row: 1;');
    expect(styles).toContain('.quick-check-form {\n  display: grid;\n  grid-column: 2;');
    expect(styles).toContain('.quick-result {\n  grid-column: 1 / -1;');
    expect(styles).toContain('grid-column: 1 / -1;');
    expect(styles).toContain('min-height: 220px;');
    expect(styles).toContain('min-height: 100px;');
    expect(styles).not.toContain('.intro-panel');
    expect(styles).not.toContain('.use-case-strip');
    expect(styles).not.toContain('.public-contract');
    expect(styles).not.toContain('.start-router');
    expect(styles).not.toContain('.start-route');
    expect(styles).not.toContain('.hero-proof-trail');
    expect(app).toContain('document.getElementById("quick-start-copy-receipt")?.addEventListener("click", copyQuickReceipt);');
    expect(app).toContain('function quickCopyScope(event)');
    expect(app).toContain('return event?.currentTarget?.id === "quick-start-copy-receipt" ? "start" : "result";');
    expect(app).toContain('function quickCopyStatusIds(scope = "all")');
    expect(app).toContain('setCopyPanel("quick-copy-panel", "quick-copy-fallback", text);');
    expect(app).toContain('setCopyPanel("quick-start-copy-panel", "quick-start-copy-fallback", text);');
    expect(app).toContain('document.getElementById("quick-start-copy-panel")');
    expect(app).toContain('startPanel.hidden = !text;');
    expect(app).toContain('document.querySelectorAll("[data-quick-start-own]").forEach((link) => {');
    expect(app).toContain('link.addEventListener("click", startOwnQuickCheck);');
    expect(app).toContain('function startOwnQuickCheck(event, { focus = true, scroll = true, preserveHash = false } = {})');
    expect(app).not.toContain('bindStartRouter');
    expect(app).not.toContain('selectStartRoute');
    expect(app).not.toContain('copyStartRoutePlan');
    expect(app).not.toContain('function startRoutePlanText()');
    expect(app).not.toContain('ScribeBench route plan');
    expect(app).not.toContain('Route plan copied.');
    expect(app).not.toContain('Clipboard unavailable. Route plan shown here.');
    expect(app).not.toContain('function absoluteSiteHref(href)');
    expect(summarySection).not.toContain('Documentation AI only matters if the signed record stays true.');
    expect(summarySection).not.toContain('13 hospital sites');
    expect(summarySection).not.toContain('A no-account source-vs-note checker.');
    expect(summarySection).not.toContain('People holding evidence, not spectators.');
    expect(summarySection).not.toContain('A review packet first; aggregate rows only with many notes.');
    expect(summarySection).not.toContain('A public evidence workbench for AI-scribe truth checks.');
    expect(summarySection).not.toContain('Copy a QA packet, claim ask, blocker receipt, or aggregate row');
    expect(summarySection).not.toContain('signed clinical notes have to stay true');
    expect(summarySection).not.toContain('Start with one review packet; make system claims only');
    expect(summarySection).not.toContain('Turn an AI-scribe note into a review packet.');
    expect(summarySection).not.toContain('A single note gets a receipt. A big claim has to earn a row.');
    expect(summarySection).not.toContain('Paste what happened. Catch what the AI made up.');
    expect(summarySection).not.toContain('The first loaded case shows the point immediately.');
    expect(summarySection).not.toContain('CT head was negative; syncope workup started.');
  });

  it('keeps mobile navigation compact so the checker owns the first screen', () => {
    const header = html.match(/<header class="topbar">[\s\S]*?<\/header>/)?.[0] || '';

    expect(header).toContain('class="mobile-nav-menu"');
    expect(header).toContain('<summary>Menu</summary>');
    expect(header).toContain('aria-label="Mobile navigation"');
    expect(header).toContain('Check note');
    expect(styles).toContain('.mobile-nav-menu {\n  display: none;');
    expect(styles).toContain('@media (max-width: 560px)');
    expect(styles).toContain('.nav {\n    display: none;');
    expect(styles).toContain('.mobile-nav-menu {\n    display: block;');
    expect(styles).toContain('scroll-margin-top: 104px;');
    expect(app).toContain('link.closest(".mobile-nav-menu")');
    expect(app).toContain('mobileMenu.open = false;');
  });

  it('puts the mobile note checker before the longer public contract', () => {
    const mobileStyles = styles.match(/@media \(max-width: 560px\) \{[\s\S]*$/)?.[0] || '';
    const formOrder = mobileStyles.indexOf('.quick-check-form {\n    order: 3;');
    const contractOrder = mobileStyles.indexOf('.purpose-line {\n    order: 4;');
    const artifactOrder = mobileStyles.indexOf('.quick-artifact-preview {\n    order: 5;');

    expect(formOrder).toBeGreaterThan(-1);
    expect(contractOrder).toBeGreaterThan(formOrder);
    expect(artifactOrder).toBeGreaterThan(contractOrder);
    expect(mobileStyles).toContain('.quick-result {\n    order: 6;');
    expect(mobileStyles).toContain('.quick-start-strip {\n    order: 7;');
    expect(mobileStyles).toContain('.quick-entry-paths {\n    order: 8;');
  });

  it('keeps model smoke out of the first note-checking task', () => {
    const quickForm = html.match(/<form class="quick-check-form"[\s\S]*?<\/form>/)?.[0] || '';
    const labSectionStart = html.indexOf('<section class="wrap section lab-section" id="lab">');
    const labWorkbenchStart = html.indexOf('<div class="lab-shell" id="lab-workbench">');
    const modelLaneStart = html.indexOf('<div class="current-model-lane"');

    expect(quickForm).toContain('id="quick-run-local"');
    expect(quickForm).toContain('quick-form-head');
    expect(quickForm).toContain('Source-note intake');
    expect(quickForm).toContain('Check one pasted note against one source.');
    expect(quickForm).toContain('Paste your own source and AI note,');
    expect(quickForm).toContain('or reload the seeded failure');
    expect(quickForm).toContain('to see the exact catch.');
    expect(quickForm).toContain('Either path leaves a reviewer handoff.');
    expect(quickForm).toContain('quick-intake-steps');
    expect(quickForm).toContain('What the note checker needs and returns');
    expect(quickForm).toContain('Encounter source plus generated note.');
    expect(quickForm).toContain('Unsupported care and high-risk chart drift.');
    expect(quickForm).toContain('Reviewer decision, excerpts, and boundary.');
    expect(quickForm).toContain('href="#lab-workbench"');
    expect(quickForm).not.toContain('run-live-smoke-top');
    expect(quickForm).not.toContain('Smoke current models');
    expect(labSectionStart).toBeGreaterThan(-1);
    expect(labWorkbenchStart).toBeGreaterThan(labSectionStart);
    expect(modelLaneStart).toBeGreaterThan(labWorkbenchStart);
    expect(styles).toContain('.quick-form-head');
    expect(styles).toContain('.quick-intake-steps');
    expect(styles).toContain('.quick-intake-steps {\n  display: none;');
    expect(styles).toContain('.quick-intake-steps div:last-child');
    expect(app).toContain('seeded example:');
    expect(app).toContain('Replace both boxes to review your own note.');
    expect(app).toContain('return ["current-model-run-smoke"]');
  });

  it('opens second-opinion handoffs on the Lab workbench', () => {
    expect(app).toContain('window.history.replaceState(null, "", "#lab-workbench")');
    expect(app).toContain('document.getElementById("lab-workbench")');
    expect(app).toContain('Use for note review now; add aggregate rows only when comparing systems.');
    expect(app).toContain('URL: https://scribe-bench.vercel.app/#lab-workbench');
  });

  it('makes Lab copied packets reviewer-ready instead of benchmark-first', () => {
    const labStart = html.indexOf('<section class="wrap section lab-section" id="lab">');
    const demoStart = html.indexOf('<section class="wrap section split" id="demo">', labStart);
    const labSection = labStart >= 0 ? html.slice(labStart, demoStart >= 0 ? demoStart : undefined) : '';

    expect(labSection).toContain('Use the Lab only when one note needs a second read.');
    expect(labSection).toContain('lab-contract');
    expect(labSection).toContain('Use when');
    expect(labSection).toContain('Start from the browser check.');
    expect(labSection).toContain('A flagged source-note pair needs a second read.');
    expect(labSection).toContain('Run or copy the browser check.');
    expect(labSection).toContain('A live judge would help adjudicate the flagged claim.');
    expect(labSection).toContain('No ranking from a Lab call.');
    expect(labSection).toContain('Start with browser check');
    expect(labSection).toContain('Second-read intake');
    expect(labSection).toContain('Re-read the same checked source and note.');
    expect(labSection).toContain('Leave with a reviewer decision and boundary, not a score or leaderboard claim.');
    expect(labSection).toContain('Checked source + note');
    expect(labSection).toContain('No-key first, live optional');
    expect(labSection).toContain('Second-read QA finding');
    expect(labSection).toContain('lab-second-read-brief');
    expect(labSection).toContain('Second-read decision');
    expect(labSection).toContain('Run the no-key check before a live judge.');
    expect(labSection).toContain('Use the live judge only when a reviewer needs another read of the same source and note.');
    expect(labSection).toContain('How to decide whether to run a live second read');
    expect(labSection).toContain('No-key result');
    expect(labSection).toContain('Use first; it does not call a provider.');
    expect(labSection).toContain('sends this source and note to the configured provider');
    expect(labSection).toContain('Still a one-note QA finding, not a system claim.');
    expect(labSection).toContain('Ask live judge for review');
    expect(labSection).toContain('lab-demo-tools');
    expect(labSection).toContain('Demo tools');
    expect(labSection).toContain('Use only when you need the seeded case or a generated candidate.');
    expect(labSection).toContain('Generate demo candidate');
    expect(labSection).toContain('Provider settings (optional)');
    expect(labSection).toContain('lab-provider-archive');
    expect(labSection).toContain('id="lab-provider-tools"');
    expect(labSection).toContain('Provider diagnostics');
    expect(labSection).toContain('Show model status and smoke test');
    expect(labSection).toContain('Open provider tools');
    expect(labSection).toContain('Second-opinion models stay behind the QA finding.');
    expect(labSection).toContain('Provider status for second reads');
    expect(labSection).toContain('Test second-read path');
    expect(labSection).not.toContain('The Lab can ask a live judge or generate a');
    expect(labSection).not.toContain('Model settings and temporary key');
    expect(labSection).not.toContain('Generate candidate</button>');
    expect(labSection).not.toContain('Use live models only for a second opinion.');
    expect(labSection).not.toContain('Run one-note smoke');
    expect(labSection).not.toContain('Current free models available for smoke checks');
    expect(html).toContain('Copy second-read review');
    expect(html).toContain('Copy detailed review');
    expect(html).toContain('What to do with this result');
    expect(html).toContain('Review signal');
    expect(html).toContain('Flagged gaps');
    expect(html).toContain('Source-note issues');
    expect(html).not.toContain('Copy evidence packet');
    expect(html).not.toContain('Copy full QA summary');
    expect(app).toContain('ScribeBench note QA review');
    expect(app).toContain('ScribeBench detailed note review');
    expect(app).toContain('Seeded QA finding');
    expect(app).toContain('No-key QA finding');
    expect(app).toContain('Live second-read result');
    expect(app).toContain('function renderLabSecondReadBrief(result)');
    expect(app).toContain('A live second read is optional, not required to hold this note.');
    expect(app).toContain('The local finding already gives a reviewer a concrete source-note gap');
    expect(app).toContain('Use for another explanation; sends this source and note to ${providerLabel}.');
    expect(app).toContain('renderLabSecondReadBrief(lastLabResult);');
    expect(app).toContain('Use now: ${packet.nextStep}');
    expect(app).toContain('Boundary: one source-note pair, not a leaderboard row, system certification, or clinical clearance.');
    expect(app).toContain('Note says: ${detail.noteExcerpt}');
    expect(app).toContain('${label}: ${detail.sourceExcerpt}');
    expect(app).toContain('Second-read models available');
    expect(app).toContain('Smoke only');
    expect(app).toContain('Provider ready');
    expect(app).not.toContain('returned ${count} usable model');
    expect(app).not.toContain('Smoke current models');
    expect(styles).toContain('.lab-second-read-brief');
    expect(styles).toContain('.lab-second-read-grid');
    expect(styles).toContain('.lab-second-read-grid div:last-child');
  });

  it('makes the first copied note artifact reviewer-ready', () => {
    const quickSection = html.match(/<div class="quick-result" id="quick-result"[\s\S]*?<form class="quick-check-form"/)?.[0] || '';
    const evidenceIndex = quickSection.indexOf('class="quick-evidence-preview"');
    const resultActionsIndex = quickSection.indexOf('class="quick-result-actions"');
    const snapshotIndex = quickSection.indexOf('class="quick-result-snapshot"');
    const copyPanelIndex = quickSection.indexOf('class="quick-copy-panel"');
    const handoffIndex = quickSection.indexOf('class="quick-review-handoff"');
    const useRouterIndex = quickSection.indexOf('class="quick-use-router"');
    const destinationIndex = quickSection.indexOf('class="quick-destination-panel"');
    const receiptPreviewIndex = quickSection.indexOf('class="quick-receipt-preview"');
    const detailsIndex = quickSection.indexOf('class="quick-result-details"');

    expect(quickSection).toContain('Copy QA finding');
    expect(quickSection).toContain('quick-result-snapshot');
    expect(quickSection).toContain('id="quick-result-issue-count"');
    expect(quickSection).toContain('id="quick-result-issue-types"');
    expect(quickSection).toContain('id="quick-result-boundary"');
    expect(quickSection).toContain('class="quick-review-handoff"');
    expect(quickSection).toContain('Reviewer handoff');
    expect(quickSection).toContain('id="quick-handoff-action"');
    expect(quickSection).toContain('id="quick-handoff-why"');
    expect(quickSection).toContain('id="quick-handoff-evidence"');
    expect(quickSection).toContain('id="quick-handoff-next"');
    expect(quickSection).toContain('class="quick-evidence-preview"');
    expect(quickSection).toContain('First source-note gap');
    expect(quickSection).toContain('id="quick-evidence-note"');
    expect(quickSection).toContain('id="quick-evidence-source"');
    expect(quickSection).toContain('id="quick-evidence-next"');
    expect(quickSection).toContain('class="quick-result-actions"');
    expect(quickSection).toContain('id="quick-copy-receipt"');
    expect(quickSection).toContain('class="quick-copy-contract"');
    expect(quickSection).toContain('id="quick-copy-contract"');
    expect(quickSection).toContain('Copied packet includes action, evidence, next step, and boundary.');
    expect(quickSection).toContain('class="quick-copy-panel"');
    expect(quickSection).toContain('id="quick-copy-panel"');
    expect(quickSection).toContain('Select this QA finding and paste it into the next review thread.');
    expect(quickSection).toContain('id="quick-copy-fallback"');
    expect(quickSection).toContain('Ask second opinion');
    expect(quickSection).toContain('Next steps');
    expect(quickSection).toContain('<details class="quick-result-details">');
    expect(quickSection).toContain('id="quick-result-details-summary"');
    expect(quickSection).toContain('<details class="quick-result-boundary-detail">');
    expect(quickSection).toContain('Show what this can and cannot prove');
    expect(quickSection).toContain('<details class="quick-receipt-preview" aria-label="Copy-ready ScribeBench QA finding">');
    expect(quickSection).toContain('Full QA finding text');
    expect(quickSection).toContain('Open when copying');
    expect(quickSection).not.toContain('Preview copy-ready review packet');
    expect(quickSection).toContain('ScribeBench source-vs-note QA finding');
    expect(quickSection).toContain('Copy-ready ScribeBench QA finding');
    expect(quickSection).toContain('class="quick-destination-panel"');
    expect(quickSection).toContain('Where this goes');
    expect(quickSection).toContain('id="quick-destination-title"');
    expect(quickSection).toContain('id="quick-destination-chart"');
    expect(quickSection).toContain('Chart QA');
    expect(quickSection).toContain('Builder / vendor');
    expect(quickSection).toContain('Public claim');
    expect(quickSection).toContain('id="quick-copy-route-note"');
    expect(quickSection).toContain('Copy routing note');
    expect(quickSection).toContain('ScribeBench QA finding route');
    expect(copyPanelIndex).toBeGreaterThan(resultActionsIndex);
    expect(copyPanelIndex).toBeLessThan(handoffIndex);
    expect(handoffIndex).toBeLessThan(evidenceIndex);
    expect(evidenceIndex).toBeLessThan(snapshotIndex);
    expect(receiptPreviewIndex).toBeGreaterThan(snapshotIndex);
    expect(receiptPreviewIndex).toBeLessThan(useRouterIndex);
    expect(receiptPreviewIndex).toBeLessThan(detailsIndex);
    expect(destinationIndex).toBeGreaterThan(useRouterIndex);
    expect(destinationIndex).toBeLessThan(detailsIndex);
    expect(app).toContain('ScribeBench source-vs-note QA finding');
    expect(app).toContain('setText("quick-copy-contract", quickCopyContract({ dangerousCount, leakCount, issueTypes }));');
    expect(app).toContain('function quickCopyContract');
    expect(app).toContain('Copied packet includes the hold/edit action');
    expect(app).toContain('Copied packet includes the cleanup action');
    expect(app).toContain('Copied packet includes the clean-triage decision');
    expect(app).toContain('function renderQuickReviewHandoff');
    expect(app).toContain('function quickReviewHandoff');
    expect(app).toContain('function renderQuickEvidencePreview');
    expect(app).toContain('Start here: this is the first claim to verify before anyone trusts or signs the note.');
    expect(app).toContain('No matching support phrase found in the source text.');
    expect(app).toContain('Check the first evidence card, then open the full list for every excerpt.');
    expect(app).toContain('let quickOwnModeRequested = false;');
    expect(app).toContain('function wantsOwnQuickCheck()');
    expect(app).toContain('startOwnQuickCheck(null, { focus: false, scroll: false, preserveHash: true });');
    expect(app).toContain('function renderQuickDestination');
    expect(app).toContain('function quickDestinationGuidance');
    expect(app).toContain('function buildQuickRouteText');
    expect(app).toContain('function copyQuickRouteNote');
    expect(app).toContain('Route this before the note is trusted.');
    expect(app).toContain('Route this to output cleanup.');
    expect(app).toContain('Use this as narrow triage.');
    expect(app).toContain('Chart QA: ${destination.chart}');
    expect(app).toContain('Builder / vendor: ${destination.builder}');
    expect(app).toContain('Public claim boundary: ${destination.claim}');
    expect(app).toContain('Hold this note before signing.');
    expect(app).toContain('Use as clean triage, not clearance.');
    expect(app).toContain('function renderQuickResultSnapshot');
    expect(app).toContain('setText("quick-result-issue-count", issueCountLabel(dangerousCount));');
    expect(app).toContain('setText("quick-result-details-summary", `Show ${issueCountLabel(dangerousCount)} with note/source excerpts`);');
    expect(app).toContain('function renderQuickUseActions(result)');
    expect(app).toContain('form.addEventListener("submit", (event) => runQuickLocalReceipt(event, { revealResult: true }));');
    expect(app).toContain('function revealQuickResult()');
    expect(app).toContain('window.history.replaceState(null, "", "#quick-result");');
    expect(styles).toContain('.quick-copy-contract');
    expect(app).toContain('scrollToAnchorTarget(panel, { behavior: "smooth" });');
    expect(app).toContain('ownNote.textContent = isSeeded ? "Check your own note" : "Check another note";');
    expect(app).toContain('copy.textContent = isSeeded ? "Copy QA finding" : "Copy this QA finding";');
    expect(app).toContain('copy.className = `button ${isSeeded ? "secondary" : "primary"} compact-button`;');
    expect(app).toContain('Copy the finding and review the note.');
    expect(app).toContain('Fix or verify the flagged claim');
    expect(app).toContain('Treat this as clean triage, not clearance.');
    expect(app).toContain('Decision: ${handoff.title}');
    expect(app).toContain('Action: ${handoff.action}');
    expect(app).toContain('Why: ${handoff.why}');
    expect(app).toContain('Evidence: ${handoff.evidence}');
    expect(app).toContain('Next: ${handoff.next}');
    expect(app).toContain('Flagged source-note evidence:');
    expect(app).toContain('Boundary: one source-note pair, browser-only local check.');
    expect(app).toContain('Can support: ${meaning.canSupport}');
    expect(app).toContain('Cannot support: ${meaning.cannotSupport}');
    expect(app).toContain('Use next: ${meaning.useNext}');
    expect(app).toContain('Not: leaderboard row, system certification, or clinical clearance.');
    expect(app).toContain('Reference: https://scribe-bench.vercel.app/#quick-check');
    expect(app).toContain('setQuickCopyStatus("QA finding copied.", scope);');
    expect(app).toContain('setQuickCopyStatus("Clipboard unavailable. QA finding shown below.", scope);');
    expect(app).toContain('resetQuickArtifacts();');
    expect(app).not.toContain('publicEvidenceCardFromQuickResult');
    expect(app).not.toContain('renderPublicEvidenceCard(publicEvidenceCardFromQuickResult');
    expect(html).toContain('Challenge a claim or test the second-read path to create one concise public ask.');
    expect(evidenceIndex).toBeGreaterThan(-1);
    expect(resultActionsIndex).toBeGreaterThan(-1);
    expect(resultActionsIndex).toBeLessThan(evidenceIndex);
    expect(evidenceIndex).toBeLessThan(snapshotIndex);
  });

  it('answers the cold visitor question before repo machinery', () => {
    const guideSection = html.match(/<section class="wrap section public-guide-section" id="next-steps">[\s\S]*?<\/section>/)?.[0] || '';
    const afterReceiptIndex = guideSection.indexOf('after-receipt-grid');
    const guideGridIndex = guideSection.indexOf('guide-grid');

    expect(afterReceiptIndex).toBeGreaterThan(-1);
    expect(guideGridIndex).toBe(-1);
    expect(guideSection).toContain('After the finding');
    expect(guideSection).toContain('One checked note tells you what to do next.');
    expect(html).toContain('aria-label="Choose the ScribeBench job"');
    expect(html).toContain('I have source + note');
    expect(html).toContain('Check one AI-scribe note');
    expect(html).toContain('Paste both sides and leave with a reviewer handoff plus QA finding.');
    expect(html).toContain('Paste my note');
    expect(html).toContain('I heard a claim');
    expect(html).toContain('Challenge the promise');
    expect(html).toContain('Build evidence ask');
    expect(html).toContain('I can add proof');
    expect(html).toContain('Publish aggregate evidence');
    expect(html).toContain('Prepare row');
    expect(guideSection).toContain('ScribeBench is for people holding evidence');
    expect(guideSection).toContain('choose the smallest honest next step');
    expect(guideSection).toContain('id="public-action-kit"');
    expect(guideSection).toContain('What to do after a ScribeBench finding');
    expect(guideSection).toContain('One note');
    expect(guideSection).toContain('If the note is flagged, hold it and copy the QA finding.');
    expect(guideSection).toContain('Open finding');
    expect(guideSection).toContain('Ask second opinion');
    expect(guideSection).toContain('Public claim');
    expect(guideSection).toContain('If the claim is bigger than one note, ask for evidence.');
    expect(guideSection).toContain('Build claim ask');
    expect(guideSection).toContain('Public row');
    expect(guideSection).toContain('If you want a ranking, finish a scored aggregate row.');
    expect(guideSection).toContain('Review blocker');
    expect(guideSection).toContain('Prepare row');
    expect(guideSection).toContain('Repo');
    expect(guideSection).toContain('If someone asks what this is, say: public QA harness.');
    expect(guideSection).toContain('browser');
    expect(guideSection).toContain('scores-only evidence ledger');
    expect(readme).toContain('one note becomes a QA finding; one claim becomes an evidence ask; many declared notes can become a scores-only public row');
    expect(readme).toContain('Use this repo in public');
    expect(readme).toContain('Start with the live artifact, not the file tree');
    expect(readme).toContain('Open the [one-note checker](https://scribe-bench.vercel.app/#quick-check), paste both sides, and copy the QA finding.');
    expect(readme).toContain('Open the [claim checker](https://scribe-bench.vercel.app/#claim-check) and turn the claim into a public evidence ask.');
    expect(readme).toContain('The honest answer is "not yet."');
    expect(readme).toContain('nobody cites old rows as today\'s winner');
    expect(readme).toContain('the checker, cases, scoring code, worklog, and aggregate-only ledger behind those public artifacts');
    expect(readme).toContain('people holding evidence use ScribeBench to catch care the AI note claims but the source does not support');
    expect(readme).toContain('Clinical QA reviewers, buyers, and builders leave with a QA finding first; bigger claims have to earn aggregate rows');
    expect(readme).toContain('copy a reviewer-ready QA finding');
    expect(readme).toContain('Choose the smallest honest next step after a finding');
    expect(readme).toContain('review one note, challenge a larger claim, finish a current row, or explain the repo');
    expect(readme).toContain('Explain the repo');
    expect(readme).toContain('Copy the citation boundary');
    expect(readme).toContain("old launch rows are discussed as failure-gradient evidence, not as today's best-model claim");
    expect(readme).toContain('A no-key, copy-ready QA finding');
    expect(readme).toContain('After-the-finding guide');
    expect(readme).toContain('browser checker, model-backed Lab APIs, TypeScript evaluator, public cases, worklog, and evidence ledger');
    expect(readme).toContain('Choose the next bounded action');
    expect(readme).toContain('copy-ready QA finding with unsupported-care flags, excerpts, evidence boundary, and next ask');
    expect(styles).toContain('.after-receipt-grid');
    expect(styles).toContain('.after-receipt-actions');
    expect(styles).toContain('.quick-entry-paths');
    expect(app).not.toContain('function bindPublicActionKit()');
    expect(app).not.toContain('document.querySelectorAll("[data-public-copy]")');
    expect(app).not.toContain('button.closest("[data-public-artifact]")');
    expect(guideSection).not.toContain('guide-answer-strip');
    expect(guideSection).not.toContain('artifact-kit');
    expect(guideSection).not.toContain('data-public-copy');
    expect(guideSection).not.toContain('ScribeBench QA packet');
    expect(guideSection).not.toContain('Copy packet post');
    expect(guideSection).not.toContain('Repo receipt');
    expect(styles).not.toContain('.artifact-list .code-block');
    expect(styles).not.toContain('.artifact-list .artifact-wide');
    expect(guideSection).not.toContain('I need to review one AI-scribe note.');
    expect(guideSection).not.toContain('I need to challenge a public AI-scribe claim.');
    expect(guideSection).not.toContain('I can add evidence people can cite.');
    expect(guideSection).not.toContain('The repo is a public clinical-AI QA workbench');
    expect(guideSection).not.toContain('The site, APIs, TypeScript evaluator');
    expect(guideSection).not.toContain('review card');
    expect(readme).not.toContain('one note becomes a public evidence card');
    expect(readme).not.toContain('Share one public card');
  });

  it('keeps claim-generated evidence asks in the public-claim context', () => {
    const claimStart = html.indexOf('<section class="wrap section claim-section" id="claim-check">');
    const evidenceStart = html.indexOf('<section class="wrap section" id="leaderboard">', claimStart);
    const claimSection = claimStart >= 0 ? html.slice(claimStart, evidenceStart >= 0 ? evidenceStart : undefined) : '';
    const decisionIndex = claimSection.indexOf('claim-decision-card');
    const askIndex = claimSection.indexOf('claim-ask-preview');
    const artifactPreviewIndex = claimSection.indexOf('claim-artifact-preview');
    const intakeStepsIndex = claimSection.indexOf('claim-intake-steps');
    const presetsIndex = claimSection.indexOf('claim-presets');
    const proofDetailIndex = claimSection.indexOf('claim-proof-detail');
    const outputGridIndex = claimSection.indexOf('claim-output-grid');
    const evidencePathIndex = claimSection.indexOf('claim-evidence-path');

    expect(claimSection).toContain('Turn a vague AI-scribe claim into an evidence ask.');
    expect(claimSection).toContain('Claim-to-evidence intake');
    expect(claimSection).toContain('Turn the claim into a public ask, not a verdict.');
    expect(claimSection).toContain('One public claim or buying-room promise.');
    expect(claimSection).toContain('What the claim can support now.');
    expect(claimSection).toContain('Copyable evidence ask plus next proof step.');
    expect(claimSection).toContain('class="claim-artifact-preview"');
    expect(claimSection).toContain('Example ScribeBench evidence ask');
    expect(claimSection).toContain('Example evidence ask');
    expect(claimSection).toContain('Do not repeat "hallucination-free" without a powered row.');
    expect(claimSection).toContain('what proof would close the claim');
    expect(claimSection).toContain('class="claim-artifact-preview-grid"');
    expect(claimSection).toContain('AI scribe is hallucination-free.');
    expect(claimSection).toContain('dangerous-fabrication rate with CI');
    expect(claimSection).toContain('Evidence request, not a safety verdict.');
    expect(claimSection).toContain('Add or request a powered aggregate row.');
    expect(claimSection).toContain('data-copy-claim-ask');
    expect(claimSection).toContain('class="claim-decision-card"');
    expect(claimSection).toContain('Claim boundary');
    expect(claimSection).toContain('id="claim-decision-title"');
    expect(claimSection).toContain('Public claim evidence boundary');
    expect(claimSection).toContain('Current status');
    expect(claimSection).toContain('Closing artifact');
    expect(claimSection).toContain('Next public step');
    expect(claimSection).toContain('id="claim-decision-primary"');
    expect(claimSection).toContain('id="claim-decision-secondary"');
    expect(claimSection).toContain('Copyable public ask');
    expect(claimSection).toContain('Paste this into the next diligence thread.');
    expect(claimSection).toContain('id="copy-claim-ask-output"');
    expect(claimSection).toContain('class="claim-ask-preview-actions"');
    expect(claimSection).toContain('id="claim-output-copy-status"');
    expect(claimSection).toContain('<pre class="code-block"><code id="claim-public-ask"></code></pre>');
    expect(claimSection).toContain('class="claim-copy-panel"');
    expect(claimSection).toContain('id="claim-copy-panel"');
    expect(claimSection).toContain('Manual copy fallback');
    expect(claimSection).toContain('Select this public ask and paste it into the next diligence thread.');
    expect(claimSection).toContain('id="claim-copy-fallback"');
    expect(claimSection).toContain('<details class="claim-proof-detail">');
    expect(claimSection).toContain('Show proof requirements and current limits');
    expect(claimSection).toContain('<details class="claim-evidence-path"');
    expect(artifactPreviewIndex).toBeGreaterThan(-1);
    expect(intakeStepsIndex).toBeGreaterThan(artifactPreviewIndex);
    expect(presetsIndex).toBeGreaterThan(intakeStepsIndex);
    expect(decisionIndex).toBeGreaterThan(-1);
    expect(askIndex).toBeGreaterThan(-1);
    expect(decisionIndex).toBeLessThan(askIndex);
    expect(proofDetailIndex).toBeGreaterThan(askIndex);
    expect(outputGridIndex).toBeGreaterThan(proofDetailIndex);
    expect(askIndex).toBeLessThan(evidencePathIndex);
    expect(html).toContain('id="public-card-claim-link"');
    expect(html).toContain('id="public-card-row-link"');
    expect(app).toContain('renderPublicEvidenceCard(publicEvidenceCardFromClaim(guide, claim), { scroll: true });');
    expect(app).toContain('kind: "claim"');
    expect(app).toContain('function renderClaimDecisionCard(guide, path)');
    expect(app).toContain('setText("claim-decision-title", path.title);');
    expect(app).toContain('setClaimEvidenceLink("claim-decision-primary", path.primary);');
    expect(app).toContain('function claimCopyScope(event)');
    expect(app).toContain('return event?.currentTarget?.id === "copy-claim-ask" ? "form" : "output";');
    expect(app).toContain('"claim-copy-status", "claim-output-copy-status"');
    expect(app).toContain('Public ask shown in the answer panel.');
    expect(app).toContain('document.getElementById("claim-copy-panel")');
    expect(app).toContain('document.querySelectorAll("[data-copy-claim-ask]").forEach((button) => {');
    expect(app).toContain('function renderPublicEvidenceCardActions(card)');
    expect(app).toContain('copy.textContent = isClaimCard ? "Copy claim ask" : "Copy evidence ask";');
    expect(app).toContain('ownNote.textContent = isClaimCard ? "Check source-note pair" : "Check your own note";');
    expect(styles).toContain('.claim-form-head');
    expect(styles).toContain('.claim-intake-steps');
    expect(styles).toContain('.claim-intake-steps div:last-child');
    expect(styles).toContain('.claim-artifact-preview');
    expect(styles).toContain('.claim-artifact-preview-grid');
    expect(styles).toContain('.claim-artifact-preview-grid div:nth-child(2n)');
    expect(styles).toContain('.claim-decision-card');
    expect(styles).toContain('.claim-decision-grid');
    expect(styles).toContain('.claim-decision-grid div:last-child');
    expect(styles).toContain('.claim-ask-preview-actions');
    expect(styles).toContain('.claim-copy-panel');
    expect(styles).toContain('.claim-copy-panel[hidden]');
    expect(html).not.toContain('id="current-challenge"');
    expect(html).not.toContain('Powered-row challenge');
    expect(app).not.toContain('bindChallengePlanner');
    expect(app).not.toContain('challengePlans');
  });

  it('keeps the run section focused on aggregate row submission', () => {
    const runStart = html.indexOf('<section class="wrap section run-panel" id="run">');
    const footerStart = html.indexOf('<footer', runStart);
    const runSection = runStart >= 0 ? html.slice(runStart, footerStart >= 0 ? footerStart : undefined) : '';
    const planIndex = runSection.indexOf('Powered row requirements');
    const contractIndex = runSection.indexOf('Public row evidence contract');
    const builderIndex = runSection.indexOf('Aggregate row command builder');

    expect(runSection).toContain('Publish a scored row only when you have many notes.');
    expect(runSection).toContain('One source-note pair belongs in the checker.');
    expect(runSection).toContain('This section is only for aggregate evidence');
    expect(planIndex).toBeGreaterThan(-1);
    expect(contractIndex).toBeGreaterThan(planIndex);
    expect(builderIndex).toBeGreaterThan(contractIndex);
    expect(runSection).toContain('Aggregate row intake');
    expect(runSection).toContain('Build a scores-only evidence package, not another demo.');
    expect(runSection).toContain('Only have a claim?');
    expect(runSection).toContain('What the aggregate row builder creates');
    expect(runSection).toContain('Candidate-note JSON for one declared system and dataset.');
    expect(runSection).toContain('Scores-only row with n, judge, repeats, date, CI, and exclusions.');
    expect(runSection).toContain('A public claim needs system-level evidence, not a one-note finding.');
    expect(runSection).toContain('Private candidate-note JSON shape');
    expect(runSection).toContain('Scoring command for aggregate output');
    expect(runSection).toContain('Pull request checklist');
    expect(styles).toContain('.run-builder-head');
    expect(styles).toContain('.run-builder-contract');
    expect(styles).toContain('.run-builder-contract div:last-child');
    expect(runSection).not.toContain('Help make ScribeBench worth citing.');
    expect(runSection).not.toContain('Choose your entry point');
    expect(runSection).not.toContain('What do you have in hand?');
    expect(runSection).not.toContain('Public work queue');
    expect(runSection).not.toContain('id="public-work-queue-task"');
    expect(runSection).not.toContain('id="copy-public-work-task"');
    expect(runSection).not.toContain('Generated ScribeBench public contribution task');
    expect(app).toContain('let currentPublicWorkTask = "";');
    expect(app).toContain('function buildPublicWorkTask(run, counts)');
    expect(app).toContain('ScribeBench public contribution task');
    expect(app).toContain('status: "Only for rows"');
    expect(app).toContain('Boundary: no raw closed-model notes in the public repo; this is not a current ranking until the row is complete and reviewed.');
    expect(app).toContain('bindPublicWorkTaskCopy();');
    expect(app).toContain('document.querySelectorAll("[data-copy-public-work-task]")');
    expect(app).toContain('setPublicWorkQueueCopyStatus("Public task copied.");');
    expect(app).not.toContain('document.querySelectorAll("#copy-public-work-task');
    expect(app).not.toContain('public-work-queue-task');
  });

  it('keeps the evidence tables framed as claim-boundary ledgers', () => {
    const leaderboardSection = html.match(/<section class="wrap section" id="leaderboard">[\s\S]*?<\/section>/)?.[0] || '';
    const taskIndex = leaderboardSection.indexOf('evidence-task-card');
    const answerIndex = leaderboardSection.indexOf('evidence-answer');
    const currentRunIndex = leaderboardSection.indexOf('current-run-card');
    const worklogIndex = leaderboardSection.indexOf('worklog-board');
    const historicalArchiveIndex = leaderboardSection.indexOf('historical-baseline-board evidence-archive');
    const smokeArchiveIndex = leaderboardSection.indexOf('evidence-archive smoke-archive');

    expect(leaderboardSection).toContain('Use it for a QA finding first; use rows only to bound claims.');
    expect(leaderboardSection).toContain('A visitor can paste one source-note pair and leave with a QA finding.');
    expect(taskIndex).toBeGreaterThan(-1);
    expect(answerIndex).toBeGreaterThan(-1);
    expect(answerIndex).toBeLessThan(taskIndex);
    expect(currentRunIndex).toBeGreaterThan(taskIndex);
    expect(historicalArchiveIndex).toBeGreaterThan(worklogIndex);
    expect(smokeArchiveIndex).toBeGreaterThan(historicalArchiveIndex);
    expect(leaderboardSection).toContain('Useful now');
    expect(leaderboardSection).toContain('Use the checker today. Do not cite a current winner yet.');
    expect(leaderboardSection).toContain('This ledger has one job: separate what a visitor can use now');
    expect(leaderboardSection).toContain('Make comparison citable');
    expect(leaderboardSection).toContain('Copy current-row task');
    expect(leaderboardSection).toContain('id="copy-current-row-task"');
    expect(leaderboardSection).toContain('data-copy-public-work-task');
    expect(leaderboardSection).toContain('id="evidence-task-title"');
    expect(leaderboardSection).toContain('id="evidence-task-bring"');
    expect(leaderboardSection).toContain('id="current-run-task-copy-status"');
    expect(leaderboardSection).toContain('Start note review');
    expect(leaderboardSection).toContain('Check claim boundary');
    expect(leaderboardSection).toContain('Copy citation boundary');
    expect(leaderboardSection).toContain('Use: one-note QA finding');
    expect(leaderboardSection).toContain('Do not cite: current winner');
    expect(leaderboardSection).toContain('Make citable: current row');
    expect(leaderboardSection).toContain('Archive only');
    expect(leaderboardSection).toContain('id="copy-citation-boundary"');
    expect(leaderboardSection).toContain('id="citation-boundary-copy-status"');
    expect(leaderboardSection).toContain('id="citation-boundary-copy-panel"');
    expect(leaderboardSection).toContain('Copied ScribeBench citation boundary');
    expect(leaderboardSection).toContain('Select this citation boundary and paste it wherever the rows are being discussed.');
    expect(leaderboardSection).toContain('Current-row blocker');
    expect(leaderboardSection).toContain('Historical failure gradient');
    expect(leaderboardSection).toContain('current best-scribe ranking is not citable');
    expect(leaderboardSection).toContain('Finish the current row before ranking anyone.');
    expect(leaderboardSection).toContain('Need 21 more scored PriMock57 cases');
    expect(leaderboardSection).toContain('A non-capped OpenRouter key, credits, or another declared provider.');
    expect(leaderboardSection).toContain('id="current-run-task-title"');
    expect(leaderboardSection).toContain('id="current-run-task-bring"');
    expect(leaderboardSection).toContain('current-run-proof-strip');
    expect(leaderboardSection).toContain('What this proves');
    expect(leaderboardSection).toContain('Why it stopped');
    expect(leaderboardSection).not.toContain('id="current-run-generated"');
    expect(leaderboardSection).not.toContain('id="current-run-last-score"');
    expect(leaderboardSection).not.toContain('id="current-run-next"');
    expect(leaderboardSection).not.toContain('Loading current PriMock57 run status');
    expect(leaderboardSection).not.toContain('Loading current-run status.');
    expect(leaderboardSection).not.toContain('Public evidence queue');
    expect(leaderboardSection).not.toContain('What we should run next');
    expect(leaderboardSection).not.toContain('id="evidence-queue"');
    expect(leaderboardSection).toContain('<details class="historical-baseline-board evidence-archive"');
    expect(leaderboardSection).toContain('Show launch rows, not the current leaderboard');
    expect(leaderboardSection).toContain('Open historical table');
    expect(leaderboardSection).toContain('Closed by default because these are June 2026 generic-scribe baselines.');
    expect(leaderboardSection).toContain('<details class="evidence-archive smoke-archive"');
    expect(leaderboardSection).toContain('Show smoke rows, never ranked evidence');
    expect(leaderboardSection).toContain('Open smoke table');
    expect(leaderboardSection).toContain('Closed by default because these n=3 synthetic rows only prove the scoring');
    expect(leaderboardSection).toContain('Claim boundary');
    expect(leaderboardSection).toContain("Historical rows can support a failure-gradient claim only; they cannot crown today's best AI scribe.");
    expect(leaderboardSection).toContain('Smoke rows prove plumbing on tiny synthetic sets; they are never ranked evidence.');
    expect(app).toContain('setText("current-run-task-title"');
    expect(app).toContain('setText("current-run-task-copy"');
    expect(app).toContain('setText("current-run-task-done"');
    expect(app).toContain('This is the public current-row blocker, not a current model result.');
    expect(app).toContain('Use this as a blocker status, not as a ranking.');
    expect(app).not.toContain('setText("current-run-generated"');
    expect(app).not.toContain('setText("current-run-last-score"');
    expect(app).not.toContain('setText("current-run-next"');
    expect(app).toContain('document.querySelectorAll("[data-copy-public-work-task]")');
    expect(app).toContain('function bindCitationBoundaryCopy()');
    expect(app).toContain('document.getElementById("copy-citation-boundary")?.addEventListener("click", copyCitationBoundary);');
    expect(app).toContain('ScribeBench citation boundary');
    expect(app).toContain('Do not cite: a current best-model ranking, safety certification, clinical clearance, or buying-guide winner from the old rows.');
    expect(app).toContain('bindCitationBoundaryCopy();');
    expect(app).toContain('setText("evidence-task-title"');
    expect(app).toContain('setText("evidence-task-bring"');
    expect(app).toContain('const evidenceTaskStatus = document.getElementById("evidence-task-status");');
    expect(app).toContain('const statusLabel = ranked ? "Historical only" : "Smoke only";');
    expect(app).toContain('const statusDetail = ranked ? `Baseline ${index + 1}; not current ranking` : "Plumbing proof; not ranked";');
  });
});
