import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const html = readFileSync(new URL('../site/index.html', import.meta.url), 'utf8');
const app = readFileSync(new URL('../site/app.js', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../site/styles.css', import.meta.url), 'utf8');
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');

describe('site copy and labels', () => {
  it('keeps quick-check result ownership dynamic instead of demo-labeled', () => {
    expect(html).toContain('id="quick-result-label"');
    expect(html).not.toContain('>Default artifact<');
    expect(app).toContain('setText("quick-result-label", quickResultLabel(result));');
    expect(app).toContain('function quickResultLabel(result)');
    expect(app).toContain('"Your QA packet"');
    expect(app).toContain('"Seeded example receipt"');
  });

  it('uses hero space to route visitors to the artifact they need', () => {
    const summarySection = html.match(/<section class="summary-band">[\s\S]*?<\/section>/)?.[0] || '';
    const introIndex = summarySection.indexOf('class="intro-panel"');
    const useCaseIndex = summarySection.indexOf('class="use-case-strip"');
    const publicContractIndex = summarySection.indexOf('class="public-contract"');
    const routerIndex = summarySection.indexOf('class="start-router"');
    const quickCheckIndex = summarySection.indexOf('class="quick-check-panel"');
    const proofIndex = summarySection.indexOf('class="hero-proof-trail"');

    expect(summarySection).toContain('NapierMD public clinical AI QA');
    expect(summarySection).toContain('Check whether an AI scribe invented care.');
    expect(summarySection).toContain('Paste the source encounter and AI-written note.');
    expect(summarySection).toContain('If the note asserts');
    expect(summarySection).toContain('care the source does not support');
    expect(summarySection).toContain('shows the contradiction');
    expect(summarySection).toContain('a review packet for a reviewer, vendor, or build-in-public thread');
    expect(useCaseIndex).toBeGreaterThan(introIndex);
    expect(useCaseIndex).toBeLessThan(routerIndex);
    expect(summarySection).toContain('Use ScribeBench if you need one of these outputs');
    expect(summarySection).toContain('Clinical QA');
    expect(summarySection).toContain('Check one note');
    expect(summarySection).toContain('Leave with a review packet for unsupported care.');
    expect(summarySection).toContain('Buyer or operator');
    expect(summarySection).toContain('Challenge a claim');
    expect(summarySection).toContain('Leave with the evidence ask a vendor should answer.');
    expect(summarySection).toContain('Builder or contributor');
    expect(summarySection).toContain('Publish a row');
    expect(summarySection).toContain('Leave with a blocker receipt or aggregate-row recipe.');
    expect(summarySection).toContain('Plain-English ScribeBench answer');
    expect(summarySection).toContain('Plain English');
    expect(summarySection).toContain('This is a receipt generator for AI-scribe evidence.');
    expect(summarySection).toContain('Visitors are not here to watch another polished demo.');
    expect(summarySection).toContain('leave with copy-ready');
    expect(summarySection).toContain('what happened, what it proves, and what proof is still missing');
    expect(summarySection).toContain('Who');
    expect(summarySection).toContain('Clinical QA reviewers, buyers, builders, and public clinical-AI contributors.');
    expect(summarySection).toContain('Do');
    expect(summarySection).toContain('Check one note, challenge one claim, or prepare a scored aggregate row.');
    expect(summarySection).toContain('Point');
    expect(summarySection).toContain('A fluent clinical note can still assert care that never happened.');
    expect(summarySection).toContain('one note gets a receipt; system claims need aggregate rows scored under the same rules');
    expect(routerIndex).toBeGreaterThan(useCaseIndex);
    expect(routerIndex).toBeLessThan(quickCheckIndex);
    expect(publicContractIndex).toBeGreaterThan(routerIndex);
    expect(publicContractIndex).toBeLessThan(quickCheckIndex);
    expect(proofIndex).toBeGreaterThan(publicContractIndex);
    expect(summarySection).toContain('Choose the next job');
    expect(summarySection).toContain('What do you need to leave with?');
    expect(summarySection).toContain('Pick the route that matches what you have in hand');
    expect(summarySection).toContain('I have source + note');
    expect(summarySection).toContain('I have a public claim');
    expect(summarySection).toContain('I have candidate notes');
    expect(summarySection).toContain('I see a current gap');
    expect(summarySection).toContain('Check your note');
    expect(summarySection).toContain('Copy route plan');
    expect(summarySection).toContain('start-route-copy-status');
    expect(summarySection).toContain('start-route-copy-panel');
    expect(summarySection).toContain('Select this route plan and paste it into the next thread.');
    expect(summarySection).toContain('Copied ScribeBench route plan');
    expect(summarySection).toContain('Run the no-key browser check; open the Lab only if the receipt needs a second read.');
    expect(summarySection).toContain('Read the NapierMD proof trail');
    expect(summarySection).toContain('Seeded receipt loaded:');
    expect(summarySection).toContain('Paste source + AI note. Get a receipt for invented care.');
    expect(summarySection).toContain('flagged claim, source contradiction, evidence boundary, and next review step');
    expect(summarySection).toContain('paste your own source-note pair in the form here');
    expect(summarySection).toContain('quick-start-strip');
    expect(summarySection).toContain('Seeded catch visible now');
    expect(summarySection).toContain('The AI note invented a negative head CT and a syncope workup.');
    expect(summarySection).toContain('Seeded source-note contradiction');
    expect(summarySection).toContain('Note says');
    expect(summarySection).toContain('CT head was negative; orthostatics, telemetry, and TSH were ordered for syncope.');
    expect(summarySection).toContain('Source says');
    expect(summarySection).toContain('Mechanical rug trip; no head strike and no loss of consciousness.');
    expect(summarySection).toContain('Your useful output is a review packet: flagged claim, source contradiction, boundary, and next step.');
    expect(summarySection).toContain('Paste your note');
    expect(summarySection).toContain('quick-start-copy-receipt');
    expect(summarySection).toContain('Copy seeded packet');
    expect(summarySection).toContain('Inspect demo receipt');
    expect(summarySection).toContain('quick-start-copy-status');
    expect(summarySection).toContain('quick-start-copy-panel');
    expect(summarySection).toContain('Manual copy fallback');
    expect(summarySection).toContain('Clipboard access is unavailable here.');
    expect(summarySection).toContain('Select this packet and paste it into the next review thread.');
    expect(summarySection).toContain('quick-start-copy-fallback');
    expect(summarySection).toContain('ScribeBench demo review packet');
    expect(styles).toContain('.quick-proof-pair');
    expect(styles).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));');
    expect(styles).toContain('.quick-proof-pair div:last-child');
    expect(styles).toContain('.use-case-strip');
    expect(styles).toContain('.use-case-strip a');
    expect(styles).toContain('.public-contract');
    expect(styles).toContain('.public-contract-grid div');
    expect(styles).toContain('.public-contract-grid div {\n    grid-template-columns: 1fr;');
    expect(styles).toContain('.quick-check-panel {\n    order: 1;');
    expect(styles).toContain('.intro-panel {\n    order: 2;');
    expect(styles).toContain('.quick-start-copy-fallback');
    expect(styles).toContain('.quick-start-copy-panel');
    expect(styles).toContain('grid-template-columns: minmax(0, 1.08fr) minmax(360px, 0.92fr);');
    expect(styles).toContain('.intro-panel {\n  grid-column: 1;\n  grid-row: 2;');
    expect(styles).toContain('.quick-check-panel {\n  grid-column: 1;\n  grid-row: 1;');
    expect(styles).toContain('.quick-check-form {\n  display: grid;\n  grid-column: 2;');
    expect(styles).toContain('#start-route-copy-status');
    expect(styles).toContain('.start-route-copy-panel');
    expect(styles).toContain('.start-route-copy-fallback');
    expect(styles).toContain('grid-column: 1 / -1;');
    expect(styles).toContain('min-height: 220px;');
    expect(styles).toContain('min-height: 150px;');
    expect(app).toContain('document.getElementById("start-route-copy-plan")?.addEventListener("click", copyStartRoutePlan);');
    expect(app).toContain('function startRoutePlanText()');
    expect(app).toContain('ScribeBench route plan');
    expect(app).toContain('Boundary: one-note receipts are useful QA; system claims need scored aggregate rows under the same rules.');
    expect(app).toContain('Route plan copied.');
    expect(app).toContain('Clipboard unavailable. Route plan shown here.');
    expect(app).toContain('function absoluteSiteHref(href)');
    expect(app).toContain('document.getElementById("quick-start-copy-receipt")?.addEventListener("click", copyQuickReceipt);');
    expect(app).toContain('"quick-copy-status", "quick-start-copy-status"');
    expect(app).toContain('"quick-copy-fallback", "quick-start-copy-fallback"');
    expect(app).toContain('document.getElementById("quick-start-copy-panel")');
    expect(app).toContain('startPanel.hidden = !text;');
    expect(app).toContain('startOwnQuickCheck(event);');
    expect(app).toContain('Check your note');
    expect(summarySection).not.toContain('Why this exists');
    expect(summarySection).not.toContain('Documentation AI only matters if the signed record stays true.');
    expect(summarySection).not.toContain('13 hospital sites');
    expect(summarySection).not.toContain('A no-account source-vs-note checker.');
    expect(summarySection).not.toContain('People holding evidence, not spectators.');
    expect(summarySection).not.toContain('A review packet first; aggregate rows only with many notes.');
    expect(summarySection).not.toContain('A public evidence workbench for AI-scribe truth checks.');
    expect(summarySection).not.toContain('Copy a QA packet, claim ask, blocker receipt, or aggregate row');
    expect(summarySection).not.toContain('signed clinical notes have to stay true');
    expect(summarySection).not.toContain('Start with one review packet; make system claims only');
    expect(summarySection).not.toContain('Turn an AI-scribe note into a review packet.');
    expect(summarySection).not.toContain('A single note gets a receipt. A big claim has to earn a row.');
    expect(summarySection).not.toContain('Paste what happened. Catch what the AI made up.');
    expect(summarySection).not.toContain('The first loaded case shows the point immediately.');
    expect(summarySection).not.toContain('CT head was negative; syncope workup started.');
  });

  it('keeps mobile navigation compact so the checker owns the first screen', () => {
    const header = html.match(/<header class="topbar">[\s\S]*?<\/header>/)?.[0] || '';

    expect(header).toContain('class="mobile-nav-menu"');
    expect(header).toContain('<summary>Menu</summary>');
    expect(header).toContain('aria-label="Mobile navigation"');
    expect(header).toContain('Check note');
    expect(styles).toContain('.mobile-nav-menu {\n  display: none;');
    expect(styles).toContain('@media (max-width: 560px)');
    expect(styles).toContain('.nav {\n    display: none;');
    expect(styles).toContain('.mobile-nav-menu {\n    display: block;');
    expect(styles).toContain('scroll-margin-top: 104px;');
    expect(app).toContain('link.closest(".mobile-nav-menu")');
    expect(app).toContain('mobileMenu.open = false;');
  });

  it('keeps model smoke out of the first note-checking task', () => {
    const quickForm = html.match(/<form class="quick-check-form"[\s\S]*?<\/form>/)?.[0] || '';
    const labSectionStart = html.indexOf('<section class="wrap section lab-section" id="lab">');
    const labWorkbenchStart = html.indexOf('<div class="lab-shell" id="lab-workbench">');
    const modelLaneStart = html.indexOf('<div class="current-model-lane"');

    expect(quickForm).toContain('id="quick-run-local"');
    expect(quickForm).toContain('href="#lab-workbench"');
    expect(quickForm).not.toContain('run-live-smoke-top');
    expect(quickForm).not.toContain('Smoke current models');
    expect(labSectionStart).toBeGreaterThan(-1);
    expect(labWorkbenchStart).toBeGreaterThan(labSectionStart);
    expect(modelLaneStart).toBeGreaterThan(labWorkbenchStart);
    expect(app).toContain('return ["current-model-run-smoke"]');
  });

  it('opens second-opinion handoffs on the Lab workbench', () => {
    expect(app).toContain('window.history.replaceState(null, "", "#lab-workbench")');
    expect(app).toContain('document.getElementById("lab-workbench")');
    expect(app).toContain('Use for note review now; add aggregate rows only when comparing systems.');
    expect(app).toContain('URL: https://scribe-bench.vercel.app/#lab-workbench');
  });

  it('makes Lab copied packets reviewer-ready instead of benchmark-first', () => {
    const labStart = html.indexOf('<section class="wrap section lab-section" id="lab">');
    const demoStart = html.indexOf('<section class="wrap section split" id="demo">', labStart);
    const labSection = labStart >= 0 ? html.slice(labStart, demoStart >= 0 ? demoStart : undefined) : '';

    expect(labSection).toContain('Use the Lab only when one note needs a second read.');
    expect(labSection).toContain('lab-contract');
    expect(labSection).toContain('Use when');
    expect(labSection).toContain('Start from the browser receipt.');
    expect(labSection).toContain('A flagged source-note pair needs a second read.');
    expect(labSection).toContain('Run or copy the browser receipt.');
    expect(labSection).toContain('A live judge would help adjudicate the flagged claim.');
    expect(labSection).toContain('No ranking from a Lab call.');
    expect(labSection).toContain('Start with browser receipt');
    expect(labSection).toContain('Ask live judge for review');
    expect(labSection).toContain('lab-demo-tools');
    expect(labSection).toContain('Demo tools');
    expect(labSection).toContain('Use only when you need the seeded case or a generated candidate.');
    expect(labSection).toContain('Generate demo candidate');
    expect(labSection).toContain('Provider settings (optional)');
    expect(labSection).toContain('lab-provider-archive');
    expect(labSection).toContain('id="lab-provider-tools"');
    expect(labSection).toContain('Provider diagnostics');
    expect(labSection).toContain('Show model status and smoke test');
    expect(labSection).toContain('Open provider tools');
    expect(labSection).toContain('Second-opinion models stay behind the receipt.');
    expect(labSection).toContain('Provider status for second reads');
    expect(labSection).toContain('Test second-read path');
    expect(labSection).not.toContain('The Lab can ask a live judge or generate a');
    expect(labSection).not.toContain('Model settings and temporary key');
    expect(labSection).not.toContain('Generate candidate</button>');
    expect(labSection).not.toContain('Use live models only for a second opinion.');
    expect(labSection).not.toContain('Run one-note smoke');
    expect(labSection).not.toContain('Current free models available for smoke checks');
    expect(html).toContain('Copy review packet');
    expect(html).toContain('Copy detailed review');
    expect(html).toContain('What to do with this result');
    expect(html).not.toContain('Copy evidence packet');
    expect(html).not.toContain('Copy full QA summary');
    expect(app).toContain('ScribeBench note review packet');
    expect(app).toContain('ScribeBench detailed note review');
    expect(app).toContain('Use now: ${packet.nextStep}');
    expect(app).toContain('Boundary: one source-note pair, not a leaderboard row, system certification, or clinical clearance.');
    expect(app).toContain('Note says: ${detail.noteExcerpt}');
    expect(app).toContain('${label}: ${detail.sourceExcerpt}');
    expect(app).toContain('Second-read models available');
    expect(app).toContain('Smoke only');
    expect(app).toContain('Provider ready');
    expect(app).not.toContain('returned ${count} usable model');
    expect(app).not.toContain('Smoke current models');
  });

  it('makes the first copied note artifact reviewer-ready', () => {
    const quickSection = html.match(/<div class="quick-result" id="quick-result"[\s\S]*?<form class="quick-check-form"/)?.[0] || '';
    const snapshotIndex = quickSection.indexOf('class="quick-result-snapshot"');
    const useRouterIndex = quickSection.indexOf('class="quick-use-router"');
    const receiptPreviewIndex = quickSection.indexOf('class="quick-receipt-preview"');
    const detailsIndex = quickSection.indexOf('class="quick-result-details"');

    expect(quickSection).toContain('Copy review packet');
    expect(quickSection).toContain('quick-result-snapshot');
    expect(quickSection).toContain('id="quick-result-issue-count"');
    expect(quickSection).toContain('id="quick-result-issue-types"');
    expect(quickSection).toContain('id="quick-result-boundary"');
    expect(quickSection).toContain('<details class="quick-result-details">');
    expect(quickSection).toContain('id="quick-result-details-summary"');
    expect(quickSection).toContain('<details class="quick-result-boundary-detail">');
    expect(quickSection).toContain('Show what this can and cannot prove');
    expect(quickSection).toContain('<details class="quick-receipt-preview" aria-label="Copy-ready ScribeBench review packet" open>');
    expect(quickSection).toContain('Review packet text');
    expect(quickSection).toContain('Visible before copy');
    expect(quickSection).not.toContain('Preview copy-ready review packet');
    expect(quickSection).toContain('ScribeBench source-vs-note review packet');
    expect(quickSection).toContain('Copy-ready ScribeBench review packet');
    expect(receiptPreviewIndex).toBeGreaterThan(snapshotIndex);
    expect(receiptPreviewIndex).toBeLessThan(useRouterIndex);
    expect(receiptPreviewIndex).toBeLessThan(detailsIndex);
    expect(app).toContain('ScribeBench note review packet');
    expect(app).toContain('function renderQuickResultSnapshot');
    expect(app).toContain('setText("quick-result-issue-count", issueCountLabel(dangerousCount));');
    expect(app).toContain('setText("quick-result-details-summary", `Show ${issueCountLabel(dangerousCount)} with note/source excerpts`);');
    expect(app).toContain('function renderQuickUseActions(result)');
    expect(app).toContain('form.addEventListener("submit", (event) => runQuickLocalReceipt(event, { revealResult: true }));');
    expect(app).toContain('function revealQuickResult()');
    expect(app).toContain('window.history.replaceState(null, "", "#quick-result");');
    expect(app).toContain('scrollToAnchorTarget(panel, { behavior: "smooth" });');
    expect(app).toContain('ownNote.textContent = isSeeded ? "Check your own note" : "Check another note";');
    expect(app).toContain('copy.textContent = isSeeded ? "Copy review packet" : "Copy this review packet";');
    expect(app).toContain('copy.className = `button ${isSeeded ? "secondary" : "primary"} compact-button`;');
    expect(app).toContain('Hold the note and copy the review packet.');
    expect(app).toContain('Fix or verify the flagged claim');
    expect(app).toContain('Treat this as clean triage, not clearance.');
    expect(app).toContain('Use now: ${useNow}');
    expect(app).toContain('Verdict: ${verdict.title}');
    expect(app).toContain('What happened: ${verdict.copy}');
    expect(app).toContain('Flagged source-note evidence:');
    expect(app).toContain('What this can support:');
    expect(app).toContain('Boundary: one source-note pair, browser-only local check, not a leaderboard row, system certification, or clinical clearance.');
    expect(app).toContain('setQuickCopyStatus("Review packet copied.");');
    expect(app).toContain('resetQuickArtifacts();');
    expect(app).not.toContain('publicEvidenceCardFromQuickResult');
    expect(app).not.toContain('renderPublicEvidenceCard(publicEvidenceCardFromQuickResult');
    expect(html).toContain('Challenge a claim or test the second-read path to create one concise public card.');
  });

  it('answers the cold visitor question before repo machinery', () => {
    const guideSection = html.match(/<section class="wrap section public-guide-section" id="next-steps">[\s\S]*?<\/section>/)?.[0] || '';
    const answerStripIndex = guideSection.indexOf('guide-answer-strip');
    const artifactKitIndex = guideSection.indexOf('artifact-kit');
    const guideGridIndex = guideSection.indexOf('guide-grid');
    const repoSystemIndex = guideSection.indexOf('guide-system');

    expect(answerStripIndex).toBeGreaterThan(-1);
    expect(guideGridIndex).toBe(-1);
    expect(answerStripIndex).toBeLessThan(artifactKitIndex);
    expect(artifactKitIndex).toBeGreaterThan(-1);
    expect(repoSystemIndex).toBeGreaterThan(artifactKitIndex);
    expect(guideSection).toContain('Leave with one artifact, not another demo screenshot.');
    expect(guideSection).toContain('The first screen already handles the note check.');
    expect(guideSection).toMatch(/packet,\s+ask,\s+blocker receipt,\s+repo receipt,\s+or aggregate row/);
    expect(guideSection).toContain('Who ScribeBench is for and why it exists');
    expect(guideSection).toContain('For whom');
    expect(guideSection).toContain('Someone with evidence in hand.');
    expect(guideSection).toContain('What to bring');
    expect(guideSection).toContain('A source-note pair, public claim, blocker, or candidate-note set.');
    expect(guideSection).toContain('Why public');
    expect(guideSection).toContain('AI-scribe claims should point back to source evidence.');
    expect(guideSection).toContain('Public action kit');
    expect(guideSection).toContain('class="artifact-kit" id="public-action-kit"');
    expect(guideSection).toContain('Pick the artifact that matches the evidence you actually have.');
    expect(guideSection).toContain('data-public-artifact');
    expect(guideSection).toContain('data-public-copy');
    expect(guideSection).toContain('Review packet');
    expect(guideSection).toContain('For one note that may have invented care.');
    expect(guideSection).toContain('ScribeBench QA packet');
    expect(guideSection).toContain('Copy packet post');
    expect(guideSection).toContain('Claim ask');
    expect(guideSection).toContain('For a vendor, model, or pilot claim.');
    expect(guideSection).toContain('Can you share ScribeBench-style evidence for this AI-scribe claim?');
    expect(guideSection).toContain('Copy claim ask');
    expect(guideSection).toContain('Blocker receipt');
    expect(guideSection).toContain('For build-in-public progress.');
    expect(guideSection).toContain('ScribeBench current-row blocker');
    expect(guideSection).toContain('Copy blocker receipt');
    expect(guideSection).toContain('Aggregate row');
    expect(guideSection).toContain('For claims about a system, not one note.');
    expect(guideSection).toContain('Submit a ScribeBench aggregate row');
    expect(guideSection).toContain('Copy row request');
    expect(guideSection).toContain('Repo receipt');
    expect(guideSection).toContain('For explaining what this project is.');
    expect(guideSection).toContain('ScribeBench repo receipt');
    expect(guideSection).toContain('Use it for: review packets, claim asks, blocker receipts, and scores-only aggregate rows.');
    expect(guideSection).toContain('Copy repo receipt');
    expect(guideSection).toContain('Open GitHub');
    expect(guideSection).toContain('Copy what is scored, what is blocked, and the exact next run task.');
    expect(guideSection).toContain('The reproducible harness behind the public artifacts.');
    expect(guideSection).toContain('ScribeBench is not an AI scribe.');
    expect(guideSection).toContain('browser receipt, claim ask, blocker receipt, optional Lab APIs');
    expect(guideSection).toContain('evaluator, public cases, worklog, repo receipt, and scores-only ledger');
    expect(guideSection).toContain('One note creates');
    expect(guideSection).toContain('a review packet; many declared notes can become an aggregate row.');
    expect(guideSection).toContain('id="public-action-status"');
    expect(guideSection).toContain('id="public-action-fallback"');
    expect(readme).toContain('one note becomes a review packet; one claim becomes an evidence ask; many declared notes can become a scores-only public row');
    expect(readme).toContain('copy a reviewer-ready review packet');
    expect(readme).toContain('Pick a visitor route');
    expect(readme).toContain('copy a short plan for what to bring, what to do, and what evidence artifact you should leave with');
    expect(readme).toContain('Choose the walk-up use case');
    expect(readme).toContain('clinical QA, buyer/operator, or builder/contributor');
    expect(readme).toContain('Explain the repo');
    expect(readme).toContain('Copy the citation boundary');
    expect(readme).toContain("old launch rows are discussed as failure-gradient evidence, not as today's best-model claim");
    expect(readme).toContain('A no-key, copy-ready review packet');
    expect(readme).toContain('repo receipt, or current-row request');
    expect(readme).toContain('browser receipt, model-backed Lab APIs, TypeScript evaluator, public cases, worklog, and evidence ledger');
    expect(readme).toContain('Share one bounded artifact');
    expect(readme).toContain('copy-ready review packet with unsupported-care flags, excerpts, evidence boundary, and next ask');
    expect(styles).toContain('.artifact-list .code-block');
    expect(styles).toContain('.artifact-list .artifact-wide');
    expect(app).toContain('function bindPublicActionKit()');
    expect(app).toContain('document.querySelectorAll("[data-public-copy]")');
    expect(app).toContain('button.closest("[data-public-artifact]")');
    expect(guideSection).not.toContain('I need to review one AI-scribe note.');
    expect(guideSection).not.toContain('I need to challenge a public AI-scribe claim.');
    expect(guideSection).not.toContain('I can add evidence people can cite.');
    expect(guideSection).not.toContain('The repo is a public clinical-AI QA workbench');
    expect(guideSection).not.toContain('The site, APIs, TypeScript evaluator');
    expect(guideSection).not.toContain('review card');
    expect(readme).not.toContain('one note becomes a public evidence card');
    expect(readme).not.toContain('Share one public card');
  });

  it('keeps claim-generated evidence cards in the public-claim context', () => {
    const claimStart = html.indexOf('<section class="wrap section claim-section" id="claim-check">');
    const evidenceStart = html.indexOf('<section class="wrap section" id="leaderboard">', claimStart);
    const claimSection = claimStart >= 0 ? html.slice(claimStart, evidenceStart >= 0 ? evidenceStart : undefined) : '';
    const askIndex = claimSection.indexOf('claim-ask-preview');
    const proofDetailIndex = claimSection.indexOf('claim-proof-detail');
    const outputGridIndex = claimSection.indexOf('claim-output-grid');
    const evidencePathIndex = claimSection.indexOf('claim-evidence-path');

    expect(claimSection).toContain('Turn a vague AI-scribe claim into an evidence ask.');
    expect(claimSection).toContain('data-copy-claim-ask');
    expect(claimSection).toContain('Copyable public ask');
    expect(claimSection).toContain('Paste this into the next diligence thread.');
    expect(claimSection).toContain('id="copy-claim-ask-output"');
    expect(claimSection).toContain('<pre class="code-block"><code id="claim-public-ask"></code></pre>');
    expect(claimSection).toContain('<details class="claim-proof-detail">');
    expect(claimSection).toContain('Show proof requirements and current limits');
    expect(claimSection).toContain('<details class="claim-evidence-path"');
    expect(askIndex).toBeGreaterThan(-1);
    expect(proofDetailIndex).toBeGreaterThan(askIndex);
    expect(outputGridIndex).toBeGreaterThan(proofDetailIndex);
    expect(askIndex).toBeLessThan(evidencePathIndex);
    expect(html).toContain('id="public-card-claim-link"');
    expect(html).toContain('id="public-card-row-link"');
    expect(app).toContain('selectStartRoute("buyer")');
    expect(app).toContain('kind: "claim"');
    expect(app).toContain('document.querySelectorAll("[data-copy-claim-ask]").forEach((button) => {');
    expect(app).toContain('function renderPublicEvidenceCardActions(card)');
    expect(app).toContain('copy.textContent = isClaimCard ? "Copy claim card" : "Copy evidence card";');
    expect(app).toContain('ownNote.textContent = isClaimCard ? "Check source-note pair" : "Check your own note";');
    expect(html).not.toContain('id="current-challenge"');
    expect(html).not.toContain('Powered-row challenge');
    expect(app).not.toContain('bindChallengePlanner');
    expect(app).not.toContain('challengePlans');
  });

  it('makes the public work queue copyable as a contribution task', () => {
    const runStart = html.indexOf('<section class="wrap section run-panel" id="run">');
    const footerStart = html.indexOf('<footer', runStart);
    const runSection = runStart >= 0 ? html.slice(runStart, footerStart >= 0 ? footerStart : undefined) : '';
    const chooserIndex = runSection.indexOf('Choose your entry point');
    const queueIndex = runSection.indexOf('Public work queue');
    const builderIndex = runSection.indexOf('Aggregate row command builder');

    expect(runSection).toContain('Help make ScribeBench worth citing.');
    expect(runSection).toContain('You do not need to be a benchmark person.');
    expect(runSection).toContain('Only many scored notes');
    expect(runSection).toContain('What do you have in hand?');
    expect(runSection).toContain('I can unblock the current run.');
    expect(runSection).toContain('Open the blocker task');
    expect(chooserIndex).toBeGreaterThan(-1);
    expect(queueIndex).toBeGreaterThan(chooserIndex);
    expect(builderIndex).toBeGreaterThan(queueIndex);
    expect(runSection).toContain('id="public-work-queue-task"');
    expect(runSection).toContain('Copyable public task');
    expect(runSection).toContain('id="copy-public-work-task"');
    expect(runSection).toContain('Generated ScribeBench public contribution task');
    expect(runSection).not.toContain('Pick the artifact before touching the builder.');
    expect(runSection).not.toContain('Start from evidence in hand');
    expect(app).toContain('let currentPublicWorkTask = "";');
    expect(app).toContain('function buildPublicWorkTask(run, counts)');
    expect(app).toContain('ScribeBench public contribution task');
    expect(app).toContain('status: "Only for rows"');
    expect(app).toContain('Boundary: no raw closed-model notes in the public repo; this is not a current ranking until the row is complete and reviewed.');
    expect(app).toContain('bindPublicWorkTaskCopy();');
    expect(app).toContain('setPublicWorkQueueCopyStatus("Public task copied.");');
  });

  it('keeps the evidence tables framed as claim-boundary ledgers', () => {
    const leaderboardSection = html.match(/<section class="wrap section" id="leaderboard">[\s\S]*?<\/section>/)?.[0] || '';
    const taskIndex = leaderboardSection.indexOf('evidence-task-card');
    const answerIndex = leaderboardSection.indexOf('evidence-answer');
    const currentRunIndex = leaderboardSection.indexOf('current-run-card');
    const worklogIndex = leaderboardSection.indexOf('worklog-board');
    const historicalArchiveIndex = leaderboardSection.indexOf('historical-baseline-board evidence-archive');
    const smokeArchiveIndex = leaderboardSection.indexOf('evidence-archive smoke-archive');

    expect(leaderboardSection).toContain('What is useful now, and what still needs public work?');
    expect(taskIndex).toBeGreaterThan(-1);
    expect(answerIndex).toBeGreaterThan(taskIndex);
    expect(currentRunIndex).toBeGreaterThan(taskIndex);
    expect(historicalArchiveIndex).toBeGreaterThan(worklogIndex);
    expect(smokeArchiveIndex).toBeGreaterThan(historicalArchiveIndex);
    expect(leaderboardSection).toContain('Make this citeable');
    expect(leaderboardSection).toContain('Copy public task');
    expect(leaderboardSection).toContain('id="copy-current-row-task"');
    expect(leaderboardSection).toContain('data-copy-public-work-task');
    expect(leaderboardSection).toContain('id="evidence-task-title"');
    expect(leaderboardSection).toContain('id="evidence-task-bring"');
    expect(leaderboardSection).toContain('id="current-run-task-copy-status"');
    expect(leaderboardSection).toContain('Use it now for note review; help finish the current row for comparisons.');
    expect(leaderboardSection).toContain('Copy citation boundary');
    expect(leaderboardSection).toContain('id="copy-citation-boundary"');
    expect(leaderboardSection).toContain('id="citation-boundary-copy-status"');
    expect(leaderboardSection).toContain('id="citation-boundary-copy-panel"');
    expect(leaderboardSection).toContain('Copied ScribeBench citation boundary');
    expect(leaderboardSection).toContain('Select this citation boundary and paste it wherever the rows are being discussed.');
    expect(leaderboardSection).toContain('Blocker receipt');
    expect(leaderboardSection).toContain('Finish the current row before ranking anyone.');
    expect(leaderboardSection).toContain('Need 21 more scored PriMock57 cases');
    expect(leaderboardSection).toContain('A non-capped OpenRouter key, credits, or another declared provider.');
    expect(leaderboardSection).toContain('id="current-run-task-title"');
    expect(leaderboardSection).toContain('id="current-run-task-bring"');
    expect(leaderboardSection).toContain('current-run-proof-strip');
    expect(leaderboardSection).toContain('What this proves');
    expect(leaderboardSection).toContain('Why it stopped');
    expect(leaderboardSection).not.toContain('id="current-run-generated"');
    expect(leaderboardSection).not.toContain('id="current-run-last-score"');
    expect(leaderboardSection).not.toContain('id="current-run-next"');
    expect(leaderboardSection).not.toContain('Loading current PriMock57 run status');
    expect(leaderboardSection).not.toContain('Loading current-run status.');
    expect(leaderboardSection).not.toContain('Public evidence queue');
    expect(leaderboardSection).not.toContain('What we should run next');
    expect(leaderboardSection).not.toContain('id="evidence-queue"');
    expect(leaderboardSection).toContain('<details class="historical-baseline-board evidence-archive"');
    expect(leaderboardSection).toContain('Show launch rows, not the current leaderboard');
    expect(leaderboardSection).toContain('Open historical table');
    expect(leaderboardSection).toContain('Closed by default because these are June 2026 generic-scribe baselines.');
    expect(leaderboardSection).toContain('<details class="evidence-archive smoke-archive"');
    expect(leaderboardSection).toContain('Show smoke rows, never ranked evidence');
    expect(leaderboardSection).toContain('Open smoke table');
    expect(leaderboardSection).toContain('Closed by default because these n=3 synthetic rows only prove the scoring');
    expect(leaderboardSection).toContain('Claim boundary');
    expect(leaderboardSection).toContain("Historical rows can support a failure-gradient claim only; they cannot crown today's best AI scribe.");
    expect(leaderboardSection).toContain('Smoke rows prove plumbing on tiny synthetic sets; they are never ranked evidence.');
    expect(app).toContain('setText("current-run-task-title"');
    expect(app).toContain('setText("current-run-task-copy"');
    expect(app).toContain('setText("current-run-task-done"');
    expect(app).toContain('This is the public blocker receipt, not a current model result.');
    expect(app).toContain('Use this as a blocker receipt, not as a ranking.');
    expect(app).not.toContain('setText("current-run-generated"');
    expect(app).not.toContain('setText("current-run-last-score"');
    expect(app).not.toContain('setText("current-run-next"');
    expect(app).toContain('document.querySelectorAll("#copy-public-work-task, [data-copy-public-work-task]")');
    expect(app).toContain('function bindCitationBoundaryCopy()');
    expect(app).toContain('document.getElementById("copy-citation-boundary")?.addEventListener("click", copyCitationBoundary);');
    expect(app).toContain('ScribeBench citation boundary');
    expect(app).toContain('Do not cite: a current best-model ranking, safety certification, clinical clearance, or buying-guide winner from the old rows.');
    expect(app).toContain('bindCitationBoundaryCopy();');
    expect(app).toContain('setText("evidence-task-title"');
    expect(app).toContain('setText("evidence-task-bring"');
    expect(app).toContain('const evidenceTaskStatus = document.getElementById("evidence-task-status");');
    expect(app).toContain('const statusLabel = ranked ? "Historical only" : "Smoke only";');
    expect(app).toContain('const statusDetail = ranked ? `Baseline ${index + 1}; not current ranking` : "Plumbing proof; not ranked";');
  });
});
